import { Product } from "./types";

const bumpaImage = (slug: string, ext = "jpg") => `/bumpa-products/${slug}.${ext}`;

export const demoProducts: Product[] = [
  { id: "bumpa-001", name: "Studless Soccer Boots", slug: "studless-soccer-boots", description: "Studless soccer boots from the current FITS Bumpa stock.", price: 57000, compareAtPrice: 60000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("studless-soccer-boots")], stock_quantity: 8, is_active: true, featured: true },
  { id: "bumpa-002", name: "Training Bips", slug: "training-bips", description: "Training bips from the current FITS Bumpa stock.", price: 15000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("training-bips")], stock_quantity: 12, is_active: true, featured: true },
  { id: "bumpa-003", name: "Jump Rope", slug: "jump-rope", description: "Jump rope with selectable options. Bumpa listed price range: ₦7,500 - ₦9,500.", price: 7500, category: "More", categorySlug: "more", sizes: ["Standard", "Premium"], images: [bumpaImage("jump-rope")], stock_quantity: 12, is_active: true },
  { id: "bumpa-004", name: "Adidas Sport Socks", slug: "adidas-sport-socks", description: "Adidas sport socks from the current FITS Bumpa stock.", price: 2500, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("adidas-sport-socks")], stock_quantity: 12, is_active: true },
  { id: "bumpa-005", name: "Cut Hose", slug: "cut-hose", description: "Cut hose from the current FITS Bumpa stock.", price: 4000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("cut-hose")], stock_quantity: 10, is_active: true },
  { id: "bumpa-006", name: "Hose Socks", slug: "hose-socks", description: "Discounted hose socks from the current FITS Bumpa stock.", price: 2000, compareAtPrice: 3000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("hose-socks")], stock_quantity: 10, is_active: true },
  { id: "bumpa-007", name: "Plain Black socks", slug: "plain-black-socks", description: "Plain black socks from the current FITS Bumpa stock.", price: 800, compareAtPrice: 850, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("plain-black-socks")], stock_quantity: 15, is_active: true },
  { id: "bumpa-008", name: "Drawstring backpack (knapsack)", slug: "drawstring-backpack-knapsack", description: "Drawstring backpack for training, class and matchday carry.", price: 2500, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("drawstring-backpack-knapsack")], stock_quantity: 10, is_active: true },
  { id: "bumpa-009", name: "Tennis Ball", slug: "tennis-ball", description: "Tennis ball from the current FITS Bumpa stock.", price: 2500, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("tennis-ball")], stock_quantity: 0, is_active: true },
  { id: "bumpa-010", name: "Sport Shorts", slug: "sport-shorts", description: "Sport shorts from the current FITS Bumpa stock.", price: 6000, category: "Football", categorySlug: "football", sizes: ["M", "L", "XL"], images: [bumpaImage("sport-shorts", "png")], stock_quantity: 8, is_active: true, featured: true },
  { id: "bumpa-011", name: "Whistle", slug: "whistle", description: "Training whistle from the current FITS Bumpa stock.", price: 2500, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("whistle")], stock_quantity: 10, is_active: true },
  { id: "bumpa-012", name: "Rugby Ball", slug: "rugby-ball", description: "Rugby ball from the current FITS Bumpa stock.", price: 15000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("rugby-ball")], stock_quantity: 0, is_active: true },
  { id: "bumpa-013", name: "Badmington Racket", slug: "badmington-racket", description: "Badmington racket from the current FITS Bumpa stock.", price: 15000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("badmington-racket")], stock_quantity: 0, is_active: true },
  { id: "bumpa-014", name: "Tennis Racket", slug: "tennis-racket", description: "Tennis racket from the current FITS Bumpa stock.", price: 20000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("tennis-racket")], stock_quantity: 0, is_active: true },
  { id: "bumpa-015", name: "Volleyball", slug: "volleyball", description: "Volleyball from the current FITS Bumpa stock.", price: 10000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("volleyball")], stock_quantity: 0, is_active: true },
  { id: "bumpa-016", name: "Ankle Support", slug: "ankle-support", description: "Ankle support from the current FITS Bumpa stock.", price: 5000, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("ankle-support")], stock_quantity: 0, is_active: true },
  { id: "bumpa-017", name: "Wrist Bands", slug: "wrist-bands", description: "Wrist bands from the current FITS Bumpa stock.", price: 5000, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("wrist-bands")], stock_quantity: 0, is_active: true },
  { id: "bumpa-018", name: "Grip Socks", slug: "grip-socks", description: "Grip socks from the current FITS Bumpa stock. Bumpa listed price range: ₦5,500 - ₦6,500.", price: 5500, category: "Football", categorySlug: "football", sizes: ["Standard", "Premium"], images: [bumpaImage("grip-socks")], stock_quantity: 0, is_active: true },
  { id: "bumpa-019", name: "Knee Sleeves", slug: "knee-sleeves", description: "Knee sleeves from the current FITS Bumpa stock.", price: 7000, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("knee-sleeves")], stock_quantity: 0, is_active: true },
  { id: "bumpa-020", name: "Arm Sleeves", slug: "arm-sleeves", description: "Arm sleeves from the current FITS Bumpa stock.", price: 4000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("arm-sleeves")], stock_quantity: 0, is_active: true },
  { id: "bumpa-021", name: "Goal keeping Gloves (Football)", slug: "goal-keeping-gloves-football", description: "Goal keeping gloves from the current FITS Bumpa stock.", price: 10000, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("goal-keeping-gloves-football")], stock_quantity: 0, is_active: true },
  { id: "bumpa-022", name: "Spalding Basketball", slug: "spalding-basketball", description: "Discounted Spalding basketball from the current FITS Bumpa stock.", price: 18000, compareAtPrice: 20000, category: "More", categorySlug: "more", sizes: ["One Size"], images: [bumpaImage("spalding-basketball")], stock_quantity: 8, is_active: true, featured: true },
  { id: "bumpa-023", name: "Soccer ball", slug: "soccer-ball", description: "Soccer ball from the current FITS Bumpa stock. Bumpa listed comparison range: ₦15,500 - ₦18,500.", price: 18000, compareAtPrice: 18500, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("soccer-ball")], stock_quantity: 0, is_active: true },
  { id: "bumpa-024", name: "Nike sport Socks", slug: "nike-sport-socks", description: "Discounted Nike sport socks from the current FITS Bumpa stock.", price: 2000, compareAtPrice: 2300, category: "Football", categorySlug: "football", sizes: ["One Size"], images: [bumpaImage("nike-sport-socks")], stock_quantity: 12, is_active: true },
  { id: "bumpa-025", name: "Cone (50 pcs)", slug: "cone-50-pcs", description: "Pack of 50 training cones from the current FITS Bumpa stock.", price: 15000, category: "Football", categorySlug: "football", sizes: ["50 pcs"], images: [bumpaImage("cone-50-pcs")], stock_quantity: 10, is_active: true },
];

export const money = (amount: number) =>
  new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(amount);
