"use client";
import { FormEvent, useState } from "react"; import { useCart } from "@/components/cart-provider"; import { money } from "@/lib/products"; import { toast } from "sonner";
const halls = ["Peter", "Joshua", "Joseph", "Daniel", "Paul", "John"] as const;

export default function Checkout() {
    const { items, subtotal } = useCart(); const [busy, setBusy] = useState(false);
    async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!items.length) return toast.error("Your bag is empty"); setBusy(true); const form = new FormData(e.currentTarget); try { const r = await fetch("/api/paystack/initialize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer: Object.fromEntries(form), items: items.map(x => ({ product_id: x.product.id, size: x.size, quantity: x.quantity })) }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); window.location.href = data.authorization_url } catch (err) { toast.error(err instanceof Error ? err.message : "Checkout failed"); setBusy(false) } }
    return <div className="page-shell"><span className="eyebrow">SECURE CHECKOUT</span><h1 className="page-title">DELIVERY DETAILS</h1><div className="checkout-grid"><form onSubmit={submit}><div className="form-grid"><label className="field"><span>Full name</span><input name="name" required /></label><label className="field"><span>Email</span><input type="email" name="email" required /></label><label className="field"><span>Phone</span><input name="phone" required /></label><label className="field"><span>Hall of residence</span><select name="hall" required defaultValue=""><option value="" disabled>Select your hall</option>{halls.map((hall) => <option key={hall} value={hall}>{hall}</option>)}</select></label><label className="field"><span>Room number</span><input name="room" pattern="[A-Za-z][0-9]{3}" title="Format: A123" placeholder="A123" required /></label></div><button disabled={busy || !items.length} className="add-button" style={{ marginTop: 25 }}>{busy ? "Preparing payment…" : `Pay ${money(subtotal)} with Paystack`}</button></form><aside className="summary"><h2>Order summary</h2>{items.map(x => <div className="summary-row" key={`${x.product.id}-${x.size}`}><span>{x.product.name} × {x.quantity}<small style={{ display: "block" }}>Size {x.size}</small></span><b>{money(x.product.price * x.quantity)}</b></div>)}<div className="total-line" style={{ marginTop: 25 }}><span>Total</span><b>{money(subtotal)}</b></div></aside></div></div>
}

