import Link from "next/link"; import { ArrowRight } from "lucide-react"; import { demoProducts } from "@/lib/products"; import { ProductCard } from "@/components/product-card"; import { HeroScene } from "@/components/hero-scene";
export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">FITS / LAGOS</span><h1>WEAR<br/>THE<br/>MOMENT.</h1><p>Football culture. Everyday uniform. Built for those who never leave the game behind.</p><Link className="button light-button" href="/products">Shop the collection <ArrowRight/></Link></div><HeroScene/></section>
 <section className="ticker" aria-label="FITS announcements"><div className="ticker-track"><span>NEW SEASON &nbsp;—&nbsp; FITS FOR LIFE &nbsp;—&nbsp; MADE IN LAGOS &nbsp;—&nbsp; BUILT FOR THE GAME &nbsp;—&nbsp;</span><span aria-hidden="true">NEW SEASON &nbsp;—&nbsp; FITS FOR LIFE &nbsp;—&nbsp; MADE IN LAGOS &nbsp;—&nbsp; BUILT FOR THE GAME &nbsp;—&nbsp;</span></div></section>
 <section className="section"><div className="section-head"><div><span className="eyebrow">SELECTED / 01</span><h2>New arrivals</h2></div><Link href="/products">View all <ArrowRight/></Link></div><div className="product-grid">{demoProducts.filter(x=>x.featured).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
 <section className="category-grid"><Link href="/products?category=Jerseys"><span>01</span><h3>JERSEYS</h3><p>On-pitch energy, off-pitch fit.</p></Link><Link href="/products?category=Sets"><span>02</span><h3>SETS</h3><p>Complete looks. Zero compromise.</p></Link><Link href="/products?category=Accessories"><span>03</span><h3>ACCESSORIES</h3><p>The finishing details.</p></Link></section>
 <section className="story" id="story"><span className="eyebrow">OUR CODE / 04</span><p>We make clothes for people who understand that football is never just ninety minutes.</p><div><h2>THE GAME<br/>DOESN&apos;T END.</h2><p>Born in Lagos. Inspired by stands, streets and the people who shape both. FITS is sport reinterpreted as a daily language.</p></div></section>
 <section className="cta"><span>FITS FOR LIFE</span><h2>YOUR NEXT<br/>UNIFORM.</h2><Link className="button light-button" href="/products">Shop now <ArrowRight/></Link></section>
 </>}
